# Generated by Django 5.2.11 on 2026-03-02 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_classroom_assignment_teacherprofile_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
