# Generated by Django 5.2.11 on 2026-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
