# Generated by Django 5.2.11 on 2026-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
    ]
