# Generated by Django 5.2.11 on 2026-03-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_assignment_semester_classroom_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
